### PR TITLE
Expose doRequest as apisauce.any() method

### PR DESCRIPTION
**Pull request by ardyfeb**
We can making request with raw config. This is usefull for making dynamic api call.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Hey @ardyfeb , thanks for the PR! Would you mind updating the documentation in the README as well with this change?

**Comment by sarahbear** [comment]
Hi, when will this feature release? Thanks!

**Comment by atistler** [comment]
Hey, any chance of releasing this in updated npm version??

**Pull request merged**
