### PR TITLE
Add documentation to cancel request

### LINKED ISSUE #246: Cancellation Request
Sorry, I know this isn't actually an issue but I was hoping that you could include how to perform a cancellation request in the documentation.

### PR DESCRIPTION
**Pull request by chakrihacker**
closes #246

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
@chakrihacker Apologies for taking so long on this -- I didn't see it until now.

Looks good to me. This API is kinda awkward, but at least people will know how to do it.

**Comment by chakrihacker** [comment]
Thanks, what do you mean by the awkward?  I have been using this and it's working greatly in my projects.

Just curious how would you cancel a request??

**Comment by jamonholmgren** [comment]
> what do you mean by the awkward

This is just my opinion, but creating a CancelToken, passing it in, and then running a method on that feels odd to me.

Ideally, one could do something like this, hanging a function off of the promise object or something:

```js
const api = create({ baseURL: 'github.com' })
const responsePromise = api.get('/users', {})
// To cancel request
responsePromise.cancel()
```

I recognize that hanging methods like `cancel` off of a promise is bad form. If one was worried about forward compatibility, we could do something like `responsePromise.apisauceCancel()`. Then, we just internally provide a cancel token and hide that implementation away from the user.

None of this is critical, though. Just an opinion.

**Pull request merged**
