### PR TITLE
Include umd build in release

### PR DESCRIPTION
**Pull request by eithe**
In https://github.com/infinitered/apisauce/pull/260 I forgot that the new umd build also needs to be included in the package.json "files" section to be included in releases. Sorry about that @chakrihacker.

Any chance you could merge this, and release as 2.1.1 or something? Thanks again for considering!

### CODE REVIEW

**Comment by chakrihacker** [comment]
Sure, can you fix indentation

**Comment by eithe** [comment]
Sure, but looks ok here?

image

**Comment by eithe** [comment]
I know it's a very far stretch, but is there any chance this could be merged and released today? I'm having a workshop/hackathon tomorrow at work to showcase how to modernize our stack, and unfortunately I forgot to actually check that the 2.1.0 release worked before today.

Please let me know if there's anything I can do regarding the indentation comment, I might just be blind  :)

**Comment by chakrihacker** [comment]
hey, sorry for the delay

**Comment by eithe** [comment]
Works brilliantly, @chakrihacker. Thanks again for including :)

**Pull request merged**
