### PR TITLE
Support delete body (also supported by Axios)

### PR DESCRIPTION
**Pull request by gbaladi**

### CODE REVIEW

**Comment by skellock** [comment]
Are you sure?

https://github.com/axios/axios/blob/4f98acc57860721c639f94f5772138b2af273301/lib/core/Axios.js#L65

(PS: i'm only reading the source code, i've never tried it)

**Comment by ebaynaud** [comment]
For me that could be merged!

**Comment by skellock** [comment]
Looks like `axios` doesn't do this but the spec doesn't prohibit this.  There's some discussion about this [SO article](https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request) .

I won't close this PR, but I would like to have more info before merging.

**Comment by ebaynaud** [comment]
@skellock how could we help? Would help me if we could merge this :)

**Comment by robinheinze** [comment]
We are trying to maintain as much parity with the Axios API as possible, so I don't believe this change is necessary, plus it would introduce breaking changes, since it changes the order of parameters for the `delete` function. 

Passing a body to `delete` is already possible by using the second parameter, which is the axios `config` object. Set `config.data` to your desired request body. For example, if you were trying to send `{ foo: "bar" }` as a request body to your DELETE request: 

```
api.delete(url, { data: { foo: "bar" } })
```

See https://github.com/axios/axios/issues/897#issuecomment-343715381 for more info.

**Comment by ebaynaud** [comment]
Thanks @robinheinze it works indeed adding an additional parameter

**Comment by Donhv** [comment]
add data by 3rd param: api.delete(url, {},{ data: { foo: "bar" } })

**Pull request closed without merging**
